# Generated by Django 2.2.2 on 2019-06-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_auto_20190613_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieactor',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
