# Generated by Django 2.2.2 on 2019-06-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_auto_20190614_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedirector',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
