# Generated by Django 2.2.2 on 2019-06-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_auto_20190614_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='original_language',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movierate',
            name='rate',
            field=models.IntegerField(),
        ),
    ]
