# Generated by Django 2.2.2 on 2019-06-14 16:12

from django.db import migrations, models
import movie_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0006_auto_20190614_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=movie_app.models.movie_directory_path),
        ),
    ]
