# Generated by Django 2.2.2 on 2019-06-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0009_tokenizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierate',
            name='rate',
            field=models.FloatField(),
        ),
    ]
